# Generated by Django 4.1.1 on 2022-09-17 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='layanan',
            fields=[
                ('idlayanan', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('jenislayanan', models.CharField(max_length=10)),
                ('harga', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='paketlayanan',
            fields=[
                ('idpaketlayanan', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('jenispaket', models.CharField(max_length=10)),
                ('keteranganpaket', models.CharField(max_length=50)),
                ('harga', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='pemesanan',
            fields=[
                ('idpemesanan', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=50)),
                ('platnomor', models.CharField(max_length=11)),
                ('tanggalpesan', models.DateField()),
                ('idpaketpelanggan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.paketlayanan')),
            ],
        ),
        migrations.CreateModel(
            name='detaillayanan',
            fields=[
                ('iddetaillayanan', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('idlayanan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.layanan')),
                ('idpemesanan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.pemesanan')),
            ],
        ),
    ]
